
name: jpg mover

on:

  push:
    paths:
    - '**.jpg'
  pull_request:
    paths:
    - '**.jpg'
    
  workflow_dispatch:

jobs:

  move-jpg:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Move all jpg files
        run: mv *.jpg Images

      - name: Commit our changes
        run: |
          git config user.name 'MariaElenaVasquez'
          git config user.email 'maelvaca80@gmail.com'
          git add .
          git commit -m "JPG Mover Activated"
          git push
