name: JPG Mover

on:

  push:
    paths: 
     - '**.jpg'
  pull_request:
    paths: 
     - '**.jpg'

workflow_dispatch:

jobs:
  move-jpg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for Folder
        run: |
          if [ ! -d '/Image']
          then
            mkdir -p Image
          fi
      - name: Move .jpg file
        run: mv *.jpg Image
        
      - name: Add user info and commit changes
        run: | 
             git config user.name 'MariaElenaVasquez'
             git config user.email 'maelvaca80@gmail.com'
             git add .
             git commit -m "JPG Mover Activated"
             git push
